settings:
  ca:
    - ./ssl/ca.cert.pem
  clientCA:
    - ./ssl/ca.cert.pem

  portal:
    address: 0.0.0.0:44123
    cert: ./ssl/portal.cert.pem
    key: ./ssl/portal.key.pem

  gateway:
    device: /tmp/usbmodem
    baud: 115200
    cert: ./ssl/zip.cert.pem
    key: ./ssl/zip.key.pem
